/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizclient;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Ivan Milin
 */
public class ContestantGUI extends javax.swing.JFrame {
    
    QuizClient parent;
    private static PrintWriter pw;
    private ArrayList<QuestionAndFourAnswers> questionAndFourAnswers;
    private ArrayList<String> answersList;
    private ArrayList<String> twoOfFourAnswersFor50_50;
    private String questionFromFriend;
    
    private ArrayList<QuizMemberClient> activeMembers;
    
    String[] answer0;
    String[] answer1;
    String[] answer2;
    String[] answer3;
    
    private int numberOfTrueAnsweredQuestions;
    private int numberOfAnsweredSets;
    int questionNumber;
    /**
     * Creates new form ContestantGUI
     */
    public ContestantGUI(QuizClient parent) {
        System.out.println(parent.getUsernameFromTextField());
        this.answersList = new ArrayList<>();
        this.activeMembers = new ArrayList<>();
        this.twoOfFourAnswersFor50_50 = new ArrayList<>();
        this.parent = parent;
        this.pw = parent.getPw();
        this.numberOfTrueAnsweredQuestions = 0;
        this.questionNumber = 0;
        initComponents();
        
        //System.out.println(parent.getUsernameFromTextField());

        jButton_50_50.setEnabled(false);
        jButton_answerA.setEnabled(false);
        jButton_answerB.setEnabled(false);
        jButton_answerC.setEnabled(false);
        jButton_answerD.setEnabled(false);
        jButton_friendsHelp.setEnabled(false);
        jButton_nextQuestion.setEnabled(false);
        jButton_answersFriend.setEnabled(false);
        jCombo_presentMembers.setEnabled(false);
        jButton_changeQuestion.setEnabled(false);
        jButton_showCurrentScore.setEnabled(false);
    }

     //jTextField_helpMeFriend

    public JTextField getjTextField_helpMeFriend() {
        return jTextField_helpMeFriend;
    }

    public void setjTextField_helpMeFriend(String jTextField_helpMeFriend) {
        this.jTextField_helpMeFriend.setText(jTextField_helpMeFriend);
    }
    
    public void refreshComboBoxes(ArrayList<String> activeUsers) {
        jCombo_presentMembers.removeAllItems();
        for (String member : activeUsers) {
            jCombo_presentMembers.addItem(member);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton_showCurrentScore = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_questionField = new javax.swing.JTextArea();
        jButton_friendsHelp = new javax.swing.JButton();
        jTextField_helpMeFriend = new javax.swing.JTextField();
        jButton_changeQuestion = new javax.swing.JButton();
        jButton_50_50 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_answerA = new javax.swing.JButton();
        jButton_answerB = new javax.swing.JButton();
        jButton_answerD = new javax.swing.JButton();
        jButton_answerC = new javax.swing.JButton();
        jCombo_presentMembers = new javax.swing.JComboBox<>();
        jButton_logout = new javax.swing.JButton();
        jButton_requestQuestionSet = new javax.swing.JButton();
        jButton_nextQuestion = new javax.swing.JButton();
        jButton_answersFriend = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ContestantGUI");

        jButton_showCurrentScore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_showCurrentScore.setText("Prikazi tabelu");
        jButton_showCurrentScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showCurrentScoreActionPerformed(evt);
            }
        });

        jTextArea_questionField.setEditable(false);
        jTextArea_questionField.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea_questionField.setColumns(20);
        jTextArea_questionField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_questionField.setRows(5);
        jTextArea_questionField.setText("Dobrodošli !");
        jScrollPane1.setViewportView(jTextArea_questionField);

        jButton_friendsHelp.setText("Pomoc prijatelja");
        jButton_friendsHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_friendsHelpActionPerformed(evt);
            }
        });

        jButton_changeQuestion.setText("Zamena pitanja");
        jButton_changeQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_changeQuestionActionPerformed(evt);
            }
        });

        jButton_50_50.setText("50 / 50");
        jButton_50_50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_50_50ActionPerformed(evt);
            }
        });

        jLabel1.setText("Posalji poruku za pomoc prijatelja :");

        jButton_answerA.setText("a)");
        jButton_answerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_answerAActionPerformed(evt);
            }
        });

        jButton_answerB.setText("b)");
        jButton_answerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_answerBActionPerformed(evt);
            }
        });

        jButton_answerD.setText("d)");
        jButton_answerD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_answerDActionPerformed(evt);
            }
        });

        jButton_answerC.setText("c)");
        jButton_answerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_answerCActionPerformed(evt);
            }
        });

        jButton_logout.setText("Odjavi se");
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jButton_requestQuestionSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_requestQuestionSet.setText("Zatrazi pitanje");
        jButton_requestQuestionSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_requestQuestionSetActionPerformed(evt);
            }
        });

        jButton_nextQuestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_nextQuestion.setText("Naredno pitanje");
        jButton_nextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextQuestionActionPerformed(evt);
            }
        });

        jButton_answersFriend.setText("Odgovori");
        jButton_answersFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_answersFriendActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_answersFriend))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_nextQuestion)
                                .addGap(85, 85, 85)
                                .addComponent(jButton_requestQuestionSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_showCurrentScore))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_answerA, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jButton_answerC, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_answerB, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_answerD, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_50_50)
                                .addGap(134, 134, 134)
                                .addComponent(jButton_changeQuestion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_friendsHelp))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jCombo_presentMembers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jTextField_helpMeFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_logout)))))))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_showCurrentScore)
                    .addComponent(jButton_requestQuestionSet)
                    .addComponent(jButton_nextQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_answerA)
                    .addComponent(jButton_answerC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_answerB)
                    .addComponent(jButton_answerD))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_50_50)
                    .addComponent(jButton_changeQuestion)
                    .addComponent(jButton_friendsHelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_answersFriend)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCombo_presentMembers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_logout)
                            .addComponent(jTextField_helpMeFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_requestQuestionSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_requestQuestionSetActionPerformed
        // TODO add your handling code here:
        jButton_50_50.setEnabled(true);
        jButton_answerA.setEnabled(true);
        jButton_answerB.setEnabled(true);
        jButton_answerC.setEnabled(true);
        jButton_answerD.setEnabled(true);
        jButton_friendsHelp.setEnabled(true);
        jButton_nextQuestion.setEnabled(true);
        jCombo_presentMembers.setEnabled(true);
        jButton_answersFriend.setEnabled(true);
        jButton_changeQuestion.setEnabled(true);
        jButton_showCurrentScore.setEnabled(true);
        
        jLabel2.setText(parent.getUsernameFromTextField());
        System.out.println("Korisnik :" + jLabel2.getText() + " se ulogovao!");
        
        refreshComboBoxes(parent.getPresentMembers());
        
        String[] question_answer = (parent.getQuestionAndAnswers().get(0)).split(";");
        String question  = question_answer[0];
        String[] answers = question_answer[1].split("\\|");

        for(int i = 0; i<4; i++)
        {
            answersList.add(answers[i]);
        }

        Collections.shuffle(this.answersList);
        
        answer0 = answersList.get(0).split(",");
        answer1 = answersList.get(1).split(",");
        answer2 = answersList.get(2).split(",");
        answer3 = answersList.get(3).split(",");

        jTextArea_questionField.setText(question);
        jButton_answerA.setText(answer0[0]);
        jButton_answerB.setText(answer1[0]);
        jButton_answerC.setText(answer2[0]);
        jButton_answerD.setText(answer3[0]);

        answersList.clear();
        
        jCombo_presentMembers.removeAllItems();
        for(String member : parent.getPresentMembers())
        {
            jCombo_presentMembers.addItem(member);
        }
        
        numberOfAnsweredSets += 10;
    }//GEN-LAST:event_jButton_requestQuestionSetActionPerformed

    private void jButton_nextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextQuestionActionPerformed
        // TODO add your handling code here:
        jButton_answerA.setEnabled(true);
        jButton_answerB.setEnabled(true);
        jButton_answerC.setEnabled(true);
        jButton_answerD.setEnabled(true);
        
        questionNumber ++;
        String[] question_answer = (parent.getQuestionAndAnswers().get(questionNumber)).split(";");
        String question  = question_answer[0];
        String[] answers = question_answer[1].split("\\|");

        for(int i = 0; i<4; i++)
        {
            answersList.add(answers[i]);
        }
        
        Collections.shuffle(this.answersList);
            
        answer0 = answersList.get(0).split(",");
        answer1 = answersList.get(1).split(",");
        answer2 = answersList.get(2).split(",");
        answer3 = answersList.get(3).split(",");

        jTextArea_questionField.setText(question);
        jButton_answerA.setText(answer0[0]);
        jButton_answerB.setText(answer1[0]);
        jButton_answerC.setText(answer2[0]);
        jButton_answerD.setText(answer3[0]);

        answersList.clear();
        
        if(questionNumber == 9)
            jButton_nextQuestion.setEnabled(false);    
    }//GEN-LAST:event_jButton_nextQuestionActionPerformed
 
    private void jButton_changeQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_changeQuestionActionPerformed
        // TODO add your handling code here:
        jButton_answerA.setEnabled(true);
        jButton_answerB.setEnabled(true);
        jButton_answerC.setEnabled(true);
        jButton_answerD.setEnabled(true);
        
        String[] question_answer = (parent.getQuestionAndAnswers().get(10)).split(";");
        String question  = question_answer[0];
        String[] answers = question_answer[1].split("\\|");

        for(int i = 0; i<4; i++)
        {
            answersList.add(answers[i]);
        }
        
        Collections.shuffle(this.answersList);
            
        answer0 = answersList.get(0).split(",");
        answer1 = answersList.get(1).split(",");
        answer2 = answersList.get(2).split(",");
        answer3 = answersList.get(3).split(",");

        jTextArea_questionField.setText(question);
        jButton_answerA.setText(answer0[0]);
        jButton_answerB.setText(answer1[0]);
        jButton_answerC.setText(answer2[0]);
        jButton_answerD.setText(answer3[0]);
        
        answersList.clear();
        jButton_changeQuestion.setEnabled(false);
    }//GEN-LAST:event_jButton_changeQuestionActionPerformed

    private void jButton_answerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_answerAActionPerformed
        // TODO add your handling code here:
        numberOfTrueAnsweredQuestions  =handleAnswer(answer0[1], numberOfTrueAnsweredQuestions, jButton_answerA, jButton_answerB, jButton_answerC, jButton_answerD);
    }//GEN-LAST:event_jButton_answerAActionPerformed

    private void jButton_answerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_answerBActionPerformed
        // TODO add your handling code here:
        numberOfTrueAnsweredQuestions = handleAnswer(answer1[1], numberOfTrueAnsweredQuestions, jButton_answerA, jButton_answerB, jButton_answerC, jButton_answerD);
    }//GEN-LAST:event_jButton_answerBActionPerformed

    private void jButton_answerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_answerCActionPerformed
        // TODO add your handling code here:
        numberOfTrueAnsweredQuestions = handleAnswer(answer2[1], numberOfTrueAnsweredQuestions, jButton_answerA, jButton_answerB, jButton_answerC, jButton_answerD);
    }//GEN-LAST:event_jButton_answerCActionPerformed

    private void jButton_answerDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_answerDActionPerformed
        // TODO add your handling code here:
        numberOfTrueAnsweredQuestions  = handleAnswer(answer3[1], numberOfTrueAnsweredQuestions, jButton_answerA, jButton_answerB, jButton_answerC, jButton_answerD);
    }//GEN-LAST:event_jButton_answerDActionPerformed

    private void jButton_50_50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_50_50ActionPerformed
        // TODO add your handling code here:
        // Get the answers associated with the current question
        String[] currentAnswers = parent.getQuestionAndAnswers().get(questionNumber).split(";")[1].split("\\|");

        // Track the indices of the correct and false answers
        int correctAnswerIndex = -1;
        ArrayList<Integer> falseAnswerIndices = new ArrayList<>();

        // Loop through the answers to find the false ones and the correct one
        for (int i = 0; i < currentAnswers.length; i++) {
            String[] answerParts = currentAnswers[i].split(",");
            if (Boolean.parseBoolean(answerParts[1])) {
                // Store the index of the correct answer
                correctAnswerIndex = i;
            } else {
                // Store the indices of false answers
                falseAnswerIndices.add(i);
            }
        }

        // Shuffle the indices of the false answers
        Collections.shuffle(falseAnswerIndices);

        // Disable two out of three false answers
        for (int i = 0; i < Math.min(2, falseAnswerIndices.size()); i++) {
            disableButtonForIndex(falseAnswerIndices.get(i));
        }
        
        jButton_50_50.setEnabled(false);
    }//GEN-LAST:event_jButton_50_50ActionPerformed

    private void jButton_friendsHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_friendsHelpActionPerformed
        // TODO add your handling code here:
        String selectedMemberName = (String) jCombo_presentMembers.getSelectedItem();
        
        String porukaZaSlanje = "HelpMeFriend =" + parent.getUsernameFromTextField() +":"+ selectedMemberName +"|"+ jTextArea_questionField.getText();
             
        System.out.println(porukaZaSlanje);
        this.pw.println(porukaZaSlanje);
        
        jButton_friendsHelp.setEnabled(false);
    }//GEN-LAST:event_jButton_friendsHelpActionPerformed

    private void jButton_answersFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_answersFriendActionPerformed
        // TODO add your handling code here:
        String selectedMemberName = (String) jCombo_presentMembers.getSelectedItem();
        String answerForFriend = "";
        
        if(!jTextField_helpMeFriend.getText().equals(""))
        {
            answerForFriend = (String)jTextField_helpMeFriend.getText();
        }
        
        String porukaZaSlanje = "AnswerForFriend =" + selectedMemberName +"|"+ parent.getUsernameFromTextField() + ":" + answerForFriend;
        System.out.println(porukaZaSlanje);
        this.pw.println(porukaZaSlanje);
    }//GEN-LAST:event_jButton_answersFriendActionPerformed

    private void jButton_showCurrentScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showCurrentScoreActionPerformed
        // TODO add your handling code here:
        Object[][] data = new Object[parent.getPresentMembers().size()][1];
        String[] columnNames = {"Participant", "Score"};

        for (int i = 0; i < parent.getPresentMembers().size(); i++) {
            data[i][0] = parent.getPresentMembers().get(i);
        }
        
        // Create an instance of the ScoreTableGUI
        ScoreTableGUI scoreTableGUI = new ScoreTableGUI(data, columnNames);
    }//GEN-LAST:event_jButton_showCurrentScoreActionPerformed

    private void disableButtonForIndex(int index) 
    {
        switch (index) {
            case 0:
                jButton_answerA.setEnabled(false);
                break;
            case 1:
                jButton_answerB.setEnabled(false);
                break;
            case 2:
                jButton_answerC.setEnabled(false);
                break;
            case 3:
                jButton_answerD.setEnabled(false);
                break;
            default:
                break;
        }
}
    
    private int handleAnswer(String answer, int numberOfTrueAnsweredQuestions, JButton buttonA, JButton buttonB, JButton buttonC, JButton buttonD) 
    {
        if (answer.equals("true")) 
        {
            numberOfTrueAnsweredQuestions++;
            
            String porukaZaSlanje = "IncrementPoints =" + parent.getUsernameFromTextField() + ":" + numberOfTrueAnsweredQuestions + ":" + numberOfAnsweredSets;
            this.pw.println(porukaZaSlanje);
            System.out.println(porukaZaSlanje);
            
            JOptionPane.showMessageDialog(null, "Correct Answer!\n" + numberOfTrueAnsweredQuestions + "/10");
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Wrong Answer!\n" + numberOfTrueAnsweredQuestions + "/10");
        }
        buttonA.setEnabled(false);
        buttonB.setEnabled(false);
        buttonC.setEnabled(false);
        buttonD.setEnabled(false);
        
        return numberOfTrueAnsweredQuestions;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContestantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContestantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContestantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContestantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        QuizClient parent = new QuizClient();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContestantGUI(parent).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_50_50;
    private javax.swing.JButton jButton_answerA;
    private javax.swing.JButton jButton_answerB;
    private javax.swing.JButton jButton_answerC;
    private javax.swing.JButton jButton_answerD;
    private javax.swing.JButton jButton_answersFriend;
    private javax.swing.JButton jButton_changeQuestion;
    private javax.swing.JButton jButton_friendsHelp;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_nextQuestion;
    private javax.swing.JButton jButton_requestQuestionSet;
    private javax.swing.JButton jButton_showCurrentScore;
    private javax.swing.JComboBox<String> jCombo_presentMembers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_questionField;
    private javax.swing.JTextField jTextField_helpMeFriend;
    // End of variables declaration//GEN-END:variables
}
