package chatroomclient;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
//import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;


@SuppressWarnings("serial")
public class ChatRoomClient extends javax.swing.JFrame {

    private Socket socket;
    private BufferedReader br; // IVAN : CITAMO PORUKE OD SERVERA
    private PrintWriter pw;    // IVAN : SALJEMO PORUKE KA SERVERU 
    private ReceiveMessageFromServer rmfs; // IVAN: Nova klasa ReceiveMessageFromServer : thread u kojem cemo primati poruke od servera
                                           //       Poruke cu slati kad ja hocu (pritiskom na taster)
                                           //       A primacu poruke od servera asinhrono
    /**
     * Creates new form ChatRoomClient
     */
    
    
    // IVAN : KONSTRUKTOR SE SAM GENERISE ZA NAS - SVE IZ GUI-a dodaje se u initComponents(); 
    public ChatRoomClient() {
        initComponents();
        
    }

    //getteri i setteri za komponente koje ce nam trebati u ReceiveMessageFromServer klasi
    public JTextArea getTaReceivedMessages() {
        return taReceivedMessages;
    }
    
    public void setTaReceivedMessages(String poruka) {
        taReceivedMessages.append(poruka + "\n");
    }

    public JComboBox<String> getCbUsers() {
        return cbUsers;
    }
    
    
    public BufferedReader getBr() {
        return br;
    }
    
    public Socket getSoc() {
        return socket;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConnect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfMyName = new javax.swing.JTextField();
        btnSendUserName = new javax.swing.JButton();
        spReceivedMessages = new javax.swing.JScrollPane();
        taReceivedMessages = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cbUsers = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Room klijent");

        btnConnect.setText("Konektuj se");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        jLabel2.setText("Poruka:");
        jLabel2.setEnabled(false);

        tfMessage.setEnabled(false);

        btnSend.setText("Salji poruku");
        btnSend.setEnabled(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel3.setText("Ime:");
        jLabel3.setEnabled(false);

        tfMyName.setEnabled(false);

        btnSendUserName.setText("Udji u sobu");
        btnSendUserName.setEnabled(false);
        btnSendUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnSendUserNameActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        taReceivedMessages.setColumns(20);
        taReceivedMessages.setRows(5);
        taReceivedMessages.setEnabled(false);
        spReceivedMessages.setViewportView(taReceivedMessages);

        jLabel4.setText("U sobi:");
        jLabel4.setEnabled(false);

        cbUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prazno" }));
        cbUsers.setEnabled(false);

        jLabel1.setText("Poruke");
        jLabel1.setEnabled(false);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfMyName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSendUserName)
                        .addContainerGap(155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConnect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSend))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(spReceivedMessages)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spReceivedMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendUserName)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnect)
                    .addComponent(btnSend))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    Kada se klikne na dugme "Konektuj se" poziva se ova metoda
    */
    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        try {
            //Kreiraj novi socket (ako nije localhost, treba promeniti IP adresu)
            this.socket = new Socket("127.0.0.1", 6001);
            //napravi BufferedReader i PrintWriter kako bi slao i primao poruke
            this.br = new BufferedReader(new InputStreamReader(this.socket.getInputStream()));
            this.pw = new PrintWriter(new OutputStreamWriter(this.socket.getOutputStream()), true);
            //za prijem poruka od servera (stizace asinhrono) koristi poseban thread
            //da bismo u novom thread-u mogli da menjamo sadrzaj komponenti (npr Combo Box-a)
            //konstruktoru novog thread-a se prosledjuje this
            this.rmfs = new ReceiveMessageFromServer(this);
            Thread thr = new Thread(rmfs);
            thr.start();
            
            btnSendUserName.setEnabled(true);
            tfMyName.setEnabled(true);

        } catch (IOException ex) {
            Logger.getLogger(ChatRoomClient.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnConnectActionPerformed

    //////////SLANJE PORUKE/////////
	private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
    	if (true) {
    		if (!this.tfMyName.getText().equals("") && !this.tfMyName.getText().equals(getCbUsers().getSelectedItem())) {
    			String porukaZaIspis = "Ja" + ": " + this.tfMessage.getText();
    			String porukaZaSlanje = this.cbUsers.getSelectedItem().toString() + ": " + this.tfMessage.getText();
    			System.out.println(this.cbUsers.getItemAt(0));
    			this.taReceivedMessages.append(porukaZaIspis + "\n");    		
        		this.pw.println(porukaZaSlanje);
    		
    		} else {
    			JOptionPane.showMessageDialog(null, "Ne mozes sebi slati poruke!");
    		}
    		
    	}
    	
    	
    }//GEN-LAST:event_btnSendActionPerformed
    
    //////////SLANJE USERNAME-a/////////
    private void btnSendUserNameActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btnSendUserNameActionPerformed
           	
    	if (!this.tfMyName.getText().equals("")) {
    		this.pw.println(tfMyName.getText());
    		cbUsers.setEnabled(true);
    		tfMessage.setEnabled(true);
    		btnSend.setEnabled(true);
    		tfMyName.setEnabled(false);
    		btnSendUserName.setEnabled(false);
    	} else {
    		
    		cbUsers.setEnabled(false);
    		tfMessage.setEnabled(false);
    		btnSend.setEnabled(false);
    	}
    	
    	
    }//GEN-LAST:event_btnSendUserNameActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                } else {
                	
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatRoomClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatRoomClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatRoomClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatRoomClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatRoomClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendUserName;
    private javax.swing.JComboBox<String> cbUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane spReceivedMessages;
    private javax.swing.JTextArea taReceivedMessages;
    private javax.swing.JTextField tfMessage;
    private javax.swing.JTextField tfMyName;
    // End of variables declaration//GEN-END:variables
}
